### ISSUE TITLE
merging csv script fails

### ISSUE THREAD

**Issue by hannesaddec** [Bilbomatica-EU-GIS/SDMX_census#1]
E:\temp\CENSUS2021\SDMX_census\src-mergingCSVCountriesToEU>joinCSVCountries.py E:\temp\CENSUS2021\deliverydata20230109\input E:\temp\CENSUS2021\deliverydata20230109\output\COMBINED20230126.csv
Traceback (most recent call last):
  File "E:\temp\CENSUS2021\SDMX_census\src-mergingCSVCountriesToEU\joinCSVCountries.py", line 9, in <module>
    with open(df_out_filename, 'w', newline='', encoding='utf-8') as fout:
TypeError: file() takes at most 3 arguments (4 given)

**Comment by hannesaddec** [comment]
please also have configurable input and output paths e.g. 
#indatadir = str(sys.argv[1])
#df_out_filename = str(sys.argv[2])

**Comment by juanpelegrina** [comment]
Dear @hannesaddec, 
are you using python 2 or python 3? 
Thanks

**Comment by hannesaddec** [comment]
E:\temp\CENSUS2021\SDMX_census\src-mergingCSVCountriesToEU>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by hannesaddec** [comment]
restarted machine and worked
