### ISSUE TITLE
atom script fails 

### ISSUE THREAD

**Issue by hannesaddec** [Bilbomatica-EU-GIS/SDMX_census#2]
E:\temp\CENSUS2021\SDMX_census\src-creationATOMFeed>createATOM.py -b https://gisco-services.ec.europa.eu/pub/census/
Traceback (most recent call last):
  File "E:\temp\CENSUS2021\SDMX_census\src-creationATOMFeed\createATOM.py", line 3, in <module>
    from lxml import etree
ImportError: No module named lxml

**Comment by jolaso** [comment]
Dear @hannesaddec 
I think the problem is that the library lxml is not installed, could you install it and let us know if you are still having this error?
pip3 install lxml
Regards

**Comment by hannesaddec** [comment]
installed and worked
